name: polypass
description: A password manager written in Dart/Flutter

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  go_router: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
